build:
  environment:
    php:
      version: '8.1'
      pecl_extensions:
        - redis
        - memcached
        - pcov
    hosts:
      laravel.dev: '127.0.0.1'
    variables:
      APP_KEY: 'base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI='
      APP_ENV: 'testing'
      APP_URL: 'http://laravel.dev'
      API_HOST: 'laravel.dev'
      DB_HOST: '127.0.0.1'
      DB_DATABASE: 'scrutinizer'

      DB_USERNAME: 'root'
      DB_PASSWORD: ''
      DB_PORT: '3306'
      MONGODB_PORT: '27017'

      MAIL_DRIVER: 'log'

  services:
    mariadb: '10.8'
    mongodb: 4
  cache:
    directories:
      - node_modules
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - mysql -uroot -e 'CREATE DATABASE scrutinizer'
  tests:
    before:
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
    override:
      -
        command: composer test-coverage
        coverage:
          file: coverage.xml
          format: clover
