version: "3.9"  # optional since v1.27.0
services:

    database:
        image: mariadb
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: no
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: xcrawler

    redis:
        image: redis
