version: "3.9"  # optional since v1.27.0
services:

    mariadb:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: xcrawler
            MARIADB_PASSWORD: xcrawler
            MARIADB_DATABASE: xcrawler
        volumes:
            - ./Docker/mariadb/db:/var/lib/mysql
        restart: unless-stopped

    redis:
        image: redis
        volumes:
            - ./Docker/redis/data:/data
        restart: unless-stopped

    mongodb:
        image: mongo
        volumes:
        - ./Docker/mongodb/db:/data/db
        - ./Docker/mongodb/configdb:/data/configdb
        restart: unless-stopped

    php:
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
        #image: php:8.1
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        restart: unless-stopped
