version: "3.9"  # optional since v1.27.0
services:

    database:
        image: mariadb
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: no
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: xcrawler
        volumes:
            - ./Docker/mariadb:/var/lib/mysql
        restart: unless-stopped

    redis:
        image: redis
        ports:
            - 3308:6379
        restart: unless-stopped

    mongodb:
        image: mongo
        ports:
            - 3309:27017
        restart: unless-stopped
        volumes:
        - ./Docker/mongodb:/data/db

    php:
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
        #image: php:8.1
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
