version: "3.9"  # optional since v1.27.0
services:

    mariadb:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: xcrawler
            MARIADB_PASSWORD: xcrawler
            MARIADB_DATABASE: xcrawler
        volumes:
            - ./Docker/mariadb:/var/lib/mysql
        restart: unless-stopped

    redis:
        image: redis
        volumes:
            - ./Docker/redis:/data
        restart: unless-stopped

    mongodb:
        image: mongo
        restart: unless-stopped
        volumes:
        - ./Docker/mongodb:/data/db

    php:
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
        #image: php:8.1
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
