name: XCrawler - Build & Tests

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    # Test on Workstation
    runs-on: [ X64 ]
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Verify MySQL connection from host
        run: |
          mysql --host mysql --port 3306 -ularavel -plaravel -e "SHOW DATABASES"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: success()

      - name: Setup PHP with coverage driver
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.1'
          coverage: pcov
          tools: php-cs-fixer, phpunit

      - name: Setup application
        if: success()
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache

      - name: Prepare application
        run: |
          php artisan config:clear
          php test.php

      - name: Lint
        run: composer lint

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        if: success()
        run: |
          composer test-coverage

      - name: Coverage
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: coverage
          path: coverage.xml

      - name: upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: ./coverage.xml
