# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: XCrawler - Build & Tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]
  push:
    branches: [ develop ]
jobs:
  build_test:

    runs-on: [ ARM64 ]

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: xcrawler
        ports:
          - 3306:3306

      redis:
        image: redis
        ports:
          - 6379:6379

      mongo:
        image: mongo:bionic
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: 8.0
          extensions: mongodb-1.13, redis, pcov

      - name: Setup application
        if: success()
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install --no-ansi --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
          php artisan config:clear
          php artisan migrate:fresh

      - name: Lint
        run: composer lint

      - name: Rector
        id: rector-git-check
        run: |
        vendor/bin/rector process --ansi
        echo ::set-output name=modified::$(if git diff --exit-code --no-patch; then echo "false"; else echo "true"; fi)
        git config --global user.name 'rector-bot'
        git config --global user.email 'jooservices@gmail.com'
        echo ::set-env name=COMMIT_MESSAGE::$(git log -1 --pretty=format:"%s")

      - name: Commit Rector changes
        if: steps.rector-git-check.outputs.modified == 'true'
        run: git commit -am "[rector] ${COMMIT_MESSAGE}"

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        if: success()
        run: |
          composer test-coverage

      - name: Coverage
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: coverage
          path: coverage.xml

      - name: upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: ./coverage.xml

      - name: Notifications
        uses: act10ns/slack@v1.5.0
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          config: .github/config/slack.yml
