# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: XCrawler - Build & Tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]
  push:
    branches: [ develop ]

jobs:



  deploy_staging:
    name: Deploy to Staging
    runs-on:
      - self-hosted
      - staging
    #needs: [ test_finished ]

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build staging
        if: ${{ github.event.pull_request.type}} == 'opened'
        run: |
          BRANCH_NAME=$(bin/slugified.sh "${{ github.head_ref }}")
          rm -rf public_html/xcrawler.dynamic/$BRANCH_NAME
          git clone git@github.com:jooservices/XCrawler.git public_html/xcrawler.dynamic/$BRANCH_NAME

