# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: XCrawler - Staging deploy

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    branches: [ develop ]
    types: [closed]
  push:
    branches: [ develop ]
jobs:
  build:
    # Test on Runner 1
    runs-on: [staging]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy
        if: success()
        run: |
          ~/deploy.sh -s

      - name: Notifications
        uses: act10ns/slack@v1.5.0
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          config: .github/config/staging.yml
